project:
  type: website
  output-dir: docs

website:
  title: "EDA de Soda Stereo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: code/analysis.qmd
        text: TPF
      - href: about.qmd
        text: About

format:
  html:
    embed-resources: true
    theme: cosmo
    css: styles.css
    toc: true
